//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunarmis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hunar_DBEntities : DbContext
    {
        public Hunar_DBEntities()
            : base("name=Hunar_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<Courses_Master> Courses_Master { get; set; }
        public virtual DbSet<District_Master> District_Master { get; set; }
        public virtual DbSet<State_Master> State_Master { get; set; }
        public virtual DbSet<TrainingAgency_Master> TrainingAgency_Master { get; set; }
        public virtual DbSet<Educational_Master> Educational_Master { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tbl_UserLogin> tbl_UserLogin { get; set; }
        public virtual DbSet<Batch_Master> Batch_Master { get; set; }
        public virtual DbSet<TrainingCenter_Master> TrainingCenter_Master { get; set; }
        public virtual DbSet<tbl_Participant> tbl_Participant { get; set; }
        public virtual DbSet<tbl_Participant_Calling> tbl_Participant_Calling { get; set; }
        public virtual DbSet<Month_Master> Month_Master { get; set; }
        public virtual DbSet<Year_Master> Year_Master { get; set; }
        public virtual DbSet<Benefit_Master> Benefit_Master { get; set; }
        public virtual DbSet<JobEmployed_Master> JobEmployed_Master { get; set; }
        public virtual DbSet<LocatedKM_Master> LocatedKM_Master { get; set; }
    }
}
